name: app 
description: "A Flutter messenger."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.0.1 

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  design_system:
    path: ./packages/design_system
  flutter_svg: ^2.0.15
  flutter_svg_provider: ^1.0.7
  device_info_plus: ^12.3.0

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^6.0.0


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.png"
  windows:
    generate: true
    image_path: "assets/icons/app_icon.png" # You can use the same PNG
    icon_size: 256
  macos:
    generate: true
    image_path: "assets/icons/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/brands/
    - assets/images/drop/
    - assets/images/bottom_navbar/
    - assets/icons/


