---
services:
  postgres:
    image: postgres:14
    container_name: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: >
        pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB} &&
        psql -U $${POSTGRES_USER} -d $${POSTGRES_DB} -c "SELECT 1;" -q
      interval: 20s
      timeout: 10s
      retries: 3
      start_period: 60s
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./volumes/postgres_data:/var/lib/postgresql/data
    networks:
      - rt-messenger

  cassandra:
    image: cassandra:5.0
    container_name: cassandra
    restart: unless-stopped
    ports:
      - "9042:9042"
    env_file: .env
    volumes:
      - ./volumes/cassandra_data:/var/lib/cassandra
    healthcheck:
      test: ["CMD-SHELL", "cqlsh localhost 9042 -e 'DESCRIBE KEYSPACES' || exit 1"]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 40s
    networks:
      - rt-messenger

  rustfs:
    image: rustfs/rustfs:latest
    container_name: rustfs
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file: .env
    volumes:
      - ./volumes/rustfs_data/data:/data
      - ./volumes/rustfs_data/logs:/logs
    command: ["server"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - rt-messenger

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    env_file: .env
    ports:
      - "6379:6379"
    command: >
      redis-server
      --requirepass r13l02c1988
      --appendonly yes
      --maxmemory 512mb
      --maxmemory-policy allkeys-lru
    volumes:
      - ./volumes/redis_data:/data
    depends_on:
      postgres:
        condition: service_healthy
      cassandra:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - rt-messenger

  app:
    build:
      context: .
      dockerfile: ./docker/rust/Dockerfile.dev
    container_name: rust-server
    image: konsin1988/messenger-rust-server
    environment:
      - POSTGRES__DATABASE=${POSTGRES_DATABASE}
      - POSTGRES__USERNAME=${POSTGRES_USERNAME}
      - POSTGRES__PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES__HOST=${POSTGRES_HOST}
      - POSTGRES__PORT=${POSTGRES_PORT}
      - REDIS__HOST=${REDIS_HOST}
      - REDIS__PORT=${REDIS_PORT}
      - REDIS__PASSWORD=${REDIS_PASSWORD}
      - REDIS__TTL=${REDIS_TTL}
      - RUSTFS__ENDPOINT_URL=${RUSTFS_ENDPOINT_URL}
      - RUSTFS__ACCESS_KEY=${RUSTFS_ACCESS_KEY}
      - RUSTFS__SECRET_KEY=${RUSTFS_SECRET_KEY}
      - RUSTFS__DATA_DIR=${RUSTFS_DATA_DIR}
      - CASSANDRA__CONTACT_POINT=${CASSANDRA_CONTACT_POINT}
      - CASSANDRA__PORT=${CASSANDRA_PORT}
      - CASSANDRA__CLUSTER_NAME=${CASSANDRA_CLUSTER_NAME}
      - CASSANDRA__DATACENTER=${CASSANDRA_DATACENTER}
      - CASSANDRA__RACK=${CASSANDRA_RACK}
      - CASSANDRA__ENDPOINT_SNITCH=${CASSANDRA_ENDPOINT_SNITCH}
    ports:
      - "3000:3000"
    volumes:
      - ./app:/app
      - ./volumes/rust/cargo_cache:/usr/local/cargo/registry
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
      cassandra:
        condition: service_healthy
      rustfs:
        condition: service_healthy
    networks:
      - rt-messenger


networks:
  rt-messenger:
    name: rt-messenger
    external: true
