FROM rustlang/rust:nightly-slim

RUN apt-get update && apt-get install -y pkg-config libssl-dev protobuf-compiler && rm -rf /var/lib/apt/lists/* 

WORKDIR /app

COPY ./app /app
ENV CARGO_TARGET_DIR=/tmp/cargo-target
ENV RUST_BACKTRACE=1
RUN cargo install cargo-watch

CMD ["cargo", "watch", "-x", "run"]

