FROM rust:1.80-slim AS builder
WORKDIR /app
COPY ./app /app

RUN cargo build --release

FROM debian:bookworm-slim
WORKDIR /app

COPY --from:builder /app/target/release/app.

RUN apt-get update && apt-get install -y libssl3 ca-certificates && rm -rf /var/lib/apt/lists/*
CMD ["./app"]

